# Schemas module
from src.schemas.common import APIResponse, ErrorDetail, ErrorCode
from src.schemas.index import (
    IndexSettings,
    IndexInfo,
    IndexListResponse,
    CreateIndexRequest,
    CreateIndexResponse,
    IndexDetailResponse,
    IndexDeleteResponse,
    IndexRebuildRequest,
    IndexRebuildResponse,
    IndexStatistics,
)
from src.schemas.document import (
    DocumentInput,
    DocumentAddOptions,
    AddDocumentsRequest,
    AddDocumentsResponse,
    DocumentInfo,
    DocumentListResponse,
    DocumentDetailResponse,
    ChunkInfo,
    UpdateDocumentRequest,
    UpdateDocumentResponse,
    UpdateMetadataRequest,
    UpdateMetadataResponse,
    DeleteDocumentResponse,
    BulkDeleteRequest,
    BulkDeleteResponse,
    FileUploadResponse,
)
from src.schemas.search import (
    SearchOptions,
    SearchRequest,
    SearchResult,
    SearchResponse,
    GrepSearchRequest,
    GrepSearchResult,
    GrepSearchResponse,
    HybridSearchRequest,
    BatchSearchQuery,
    BatchSearchRequest,
    BatchSearchResponse,
)

__all__ = [
    # Common
    "APIResponse",
    "ErrorDetail",
    "ErrorCode",
    # Index
    "IndexSettings",
    "IndexInfo",
    "IndexListResponse",
    "CreateIndexRequest",
    "CreateIndexResponse",
    "IndexDetailResponse",
    "IndexDeleteResponse",
    "IndexRebuildRequest",
    "IndexRebuildResponse",
    "IndexStatistics",
    # Document
    "DocumentInput",
    "DocumentAddOptions",
    "AddDocumentsRequest",
    "AddDocumentsResponse",
    "DocumentInfo",
    "DocumentListResponse",
    "DocumentDetailResponse",
    "ChunkInfo",
    "UpdateDocumentRequest",
    "UpdateDocumentResponse",
    "UpdateMetadataRequest",
    "UpdateMetadataResponse",
    "DeleteDocumentResponse",
    "BulkDeleteRequest",
    "BulkDeleteResponse",
    "FileUploadResponse",
    # Search
    "SearchOptions",
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "GrepSearchRequest",
    "GrepSearchResult",
    "GrepSearchResponse",
    "HybridSearchRequest",
    "BatchSearchQuery",
    "BatchSearchRequest",
    "BatchSearchResponse",
]
